# Generated by Django 4.1.5 on 2023-04-19 15:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celery_id', models.UUIDField(editable=False, null=True)),
                ('request', models.JSONField()),
                ('vineyard', models.PositiveIntegerField()),
                ('vineyard_name', models.CharField(max_length=255)),
                ('year_from', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2023)])),
                ('year_to', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2023)])),
                ('status', django_mysql.models.EnumField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('FINISHED', 'Finished'), ('FAILED', 'Failed')], default='PENDING')),
                ('current', models.PositiveIntegerField(default=0, editable=False)),
                ('total', models.PositiveIntegerField(default=0, editable=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='pdf/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='TaskLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(editable=False, max_length=2048)),
                ('level', models.IntegerField(choices=[(None, '(Unknown)'), (50, 'Critical'), (40, 'Error'), (30, 'Warning'), (20, 'Info'), (10, 'Debug'), (0, 'Notset')], editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='generator.task')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
