# Generated by Django 4.2.2 on 2023-11-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_task_generator_t_updated_d63c8f_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='generator_t_updated_d63c8f_idx',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='vineyard',
            new_name='winery',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='vineyard_name',
            new_name='winery_name',
        ),
    ]
