# Generated by Django 4.1.5 on 2023-04-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileManaged',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.PositiveIntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('uri', models.CharField(db_collation='utf8mb4_bin', max_length=255, unique=True)),
                ('filemime', models.CharField(db_collation='utf8mb4_bin', max_length=255)),
                ('filesize', models.PositiveBigIntegerField()),
                ('status', models.IntegerField()),
                ('timestamp', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'file_managed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GustosWine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vineyard', models.PositiveIntegerField()),
                ('country', models.PositiveIntegerField()),
                ('series', models.PositiveIntegerField(blank=True, null=True)),
                ('include_series', models.IntegerField(blank=True, null=True)),
                ('category', models.TextField(blank=True, db_collation='utf8mb4_bin', null=True)),
                ('created', models.PositiveIntegerField()),
                ('updated', models.PositiveIntegerField()),
                ('color', models.PositiveIntegerField(blank=True, null=True)),
                ('beverage_type_secondary', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gustos_wine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GustosWineEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine', models.PositiveIntegerField()),
                ('photo', models.PositiveIntegerField(blank=True, null=True)),
                ('is_igp', models.IntegerField(blank=True, null=True)),
                ('stage_of_production', models.PositiveIntegerField(blank=True, null=True)),
                ('prod_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prod_unit', models.PositiveIntegerField(blank=True, null=True)),
                ('alcohol', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sugar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vintage', models.PositiveIntegerField()),
                ('created', models.PositiveIntegerField()),
                ('updated', models.PositiveIntegerField()),
                ('region', models.PositiveIntegerField(blank=True, null=True)),
                ('include_region', models.IntegerField(blank=True, null=True)),
                ('gwmr', models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True)),
            ],
            options={
                'db_table': 'gustos_wine_entity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GustosWineGrapes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine_entity', models.PositiveIntegerField()),
                ('grape', models.PositiveIntegerField()),
                ('percent', models.PositiveIntegerField()),
                ('wine', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'gustos_wine_grapes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaxonomyTermData',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('vid', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.IntegerField()),
                ('language', models.CharField(max_length=12)),
                ('i18n_tsid', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'taxonomy_term_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThirdPartyAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_id', models.PositiveIntegerField()),
                ('value', models.CharField(max_length=6)),
                ('weight', models.IntegerField()),
                ('min_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('photo_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.IntegerField()),
                ('updated', models.IntegerField()),
            ],
            options={
                'db_table': 'third_party_award',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThirdPartyAwardWineEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_id', models.PositiveIntegerField()),
                ('wine_entity_id', models.PositiveIntegerField()),
                ('exact_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created', models.IntegerField()),
                ('updated', models.IntegerField()),
            ],
            options={
                'db_table': 'third_party_award_wine_entity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThirdPartyCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('region', models.CharField(max_length=13)),
                ('google_page_rating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('correction_factor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.IntegerField()),
                ('updated', models.IntegerField()),
                ('logo_id', models.PositiveIntegerField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=1024, null=True)),
                ('use_parsed_page_rank', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'third_party_competition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThirdPartyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.PositiveIntegerField(blank=True, null=True)),
                ('competition_id', models.PositiveIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('wine_count', models.PositiveSmallIntegerField()),
                ('medal_count', models.PositiveSmallIntegerField()),
                ('created', models.IntegerField()),
                ('updated', models.IntegerField()),
            ],
            options={
                'db_table': 'third_party_event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThirdPartyGwmr',
            fields=[
                ('wine_entity_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('year_from', models.PositiveIntegerField()),
                ('year_to', models.PositiveIntegerField()),
                ('rating', models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True)),
            ],
            options={
                'db_table': 'third_party_gwmr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vineyard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('country', models.PositiveIntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.PositiveIntegerField()),
                ('updated', models.PositiveIntegerField()),
                ('website', models.CharField(blank=True, max_length=1024, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'vineyard',
                'managed': False,
            },
        ),
    ]
