# Generated by Django 4.2.2 on 2023-11-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gustos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_id', models.PositiveIntegerField()),
                ('value', models.CharField(max_length=6)),
                ('weight', models.IntegerField()),
                ('min_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('photo_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.IntegerField()),
                ('updated', models.IntegerField()),
            ],
            options={
                'db_table': 'award',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AwardWineEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_id', models.PositiveIntegerField()),
                ('wine_entity_id', models.PositiveIntegerField()),
                ('exact_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created', models.IntegerField()),
                ('updated', models.IntegerField()),
            ],
            options={
                'db_table': 'award_wine_entity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('region', models.CharField(max_length=13)),
                ('google_page_rating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('correction_factor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.IntegerField()),
                ('updated', models.IntegerField()),
                ('logo_id', models.PositiveIntegerField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=1024, null=True)),
                ('use_parsed_page_rank', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'competition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.PositiveIntegerField(blank=True, null=True)),
                ('competition_id', models.PositiveIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('wine_count', models.PositiveSmallIntegerField()),
                ('medal_count', models.PositiveSmallIntegerField()),
                ('created', models.IntegerField()),
                ('updated', models.IntegerField()),
            ],
            options={
                'db_table': 'event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaxonomyTerm',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('vid', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.IntegerField()),
                ('language', models.CharField(max_length=12)),
                ('i18n_tsid', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'taxonomy_term',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('winery', models.PositiveIntegerField()),
                ('country', models.PositiveIntegerField()),
                ('series', models.PositiveIntegerField(blank=True, null=True)),
                ('include_series', models.IntegerField(blank=True, null=True)),
                ('category', models.TextField(blank=True, db_collation='utf8mb4_bin', null=True)),
                ('created', models.PositiveIntegerField()),
                ('updated', models.PositiveIntegerField()),
                ('color', models.PositiveIntegerField(blank=True, null=True)),
                ('beverage_type_secondary', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WineEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine', models.PositiveIntegerField()),
                ('photo', models.PositiveIntegerField(blank=True, null=True)),
                ('is_igp', models.IntegerField(blank=True, null=True)),
                ('stage_of_production', models.PositiveIntegerField(blank=True, null=True)),
                ('prod_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prod_unit', models.PositiveIntegerField(blank=True, null=True)),
                ('alcohol', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sugar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vintage', models.PositiveIntegerField()),
                ('created', models.PositiveIntegerField()),
                ('updated', models.PositiveIntegerField()),
                ('region', models.PositiveIntegerField(blank=True, null=True)),
                ('include_region', models.IntegerField(blank=True, null=True)),
                ('gwmr', models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True)),
            ],
            options={
                'db_table': 'wine_entity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WineGrapes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine_entity', models.PositiveIntegerField()),
                ('grape', models.PositiveIntegerField()),
                ('percent', models.PositiveIntegerField()),
                ('wine', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'wine_grapes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WineGwmr',
            fields=[
                ('wine_entity_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('year_from', models.PositiveIntegerField()),
                ('year_to', models.PositiveIntegerField()),
                ('rating', models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True)),
            ],
            options={
                'db_table': 'wine_gwmr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Winery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('country', models.PositiveIntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.PositiveIntegerField()),
                ('updated', models.PositiveIntegerField()),
                ('website', models.CharField(blank=True, max_length=1024, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'winery',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='GustosWine',
        ),
        migrations.DeleteModel(
            name='GustosWineEntity',
        ),
        migrations.DeleteModel(
            name='GustosWineGrapes',
        ),
        migrations.DeleteModel(
            name='TaxonomyTermData',
        ),
        migrations.DeleteModel(
            name='ThirdPartyAward',
        ),
        migrations.DeleteModel(
            name='ThirdPartyAwardWineEntity',
        ),
        migrations.DeleteModel(
            name='ThirdPartyCompetition',
        ),
        migrations.DeleteModel(
            name='ThirdPartyEvent',
        ),
        migrations.DeleteModel(
            name='ThirdPartyGwmr',
        ),
        migrations.DeleteModel(
            name='Vineyard',
        ),
    ]
